import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'oms_full_form': 'Oil Management System',
          'login': 'Login',
          'sign_in_continue': 'Please sign in to continue',
          'user_id': 'User ID',
          'enter_username': 'Enter Username',
          'username_required': 'Username is required',
          'password': 'Password',
          'enter_password': 'Enter Password',
          'password_required': 'Password is required',
          'forgot_password': 'Forgot Password ?',
          'new_password': 'New Password',
          'new_password_req': 'New password is required',
          'change_pwd': 'Change Password',
          'sign_out': 'Sign out',
          'sign_out_prompt': 'Are you sure you want to sign out?',
          'sign_out_success': 'You have signed out successfully!',
          'sign_out_fail': 'Signout Failed!',
          'confirm_new_password': 'Confirm New Password',
          'confirm_new_password_req': 'Confirm new password is required',
          'enter_new_pwd': 'Enter New Password',
          're_enter_new_pwd': 'Re-Enter New Password',
          'next': 'Next',
          'back': 'Back',
          'no': 'No',
          'yes': 'Yes',
          'mobile_number': 'Mobile Number',
          'send_otp_desc': 'We need to send OTP to verify your number.',
          'enter_mobile_number': 'Enter mobile number',
          'mobile_number_req': 'Mobile number is required',
          'invalid_mobile_no': 'Invalid mobile number',
          'enter_otp': 'Please enter OTP',
          'enter_valid_otp': 'Please enter valid OTP',
          'otp': 'OTP',
          'sent_otp_desc': 'Please enter the OTP sent to your mobile number.',
          'fill_fuel': 'Fill Fuel',
          'reports': 'Reports',
          'fuel_fill_success': 'Fuel has been filled successfully!',
          'print': 'Print',
          'fill_fuel_confirmation': 'Are you sure you want to fill fuel ?',
          'voucher_code': 'Voucher Code',
          'enter_voucher_code': 'Enter voucher code',
          'voucher_code_cannot_empty': 'Voucher code cannot be empty',
          'tap_the_card': 'Tap the card',
          'validate': 'Validate',
          'total_available_litres': 'Total available litres',
          'total_available_amount': 'Total available amount',
          'diesel_rate_per_litre': 'Current diesel rate per litre',
          'department': 'Department',
          'designation': 'Designation',
          'fuel_type': 'Fuel type',
          'vehicle_number': 'Vehicle Number',
          'invalid_vehicle_number': "Invalid Vehicle Number",
          'enter_vehicle_number': 'Enter vehicle number',
          'vehicle_no_required': 'Vehicle number is required',
          'calculated': 'Calculated',
          'photo_required': 'Photo is required',
          'tank_number': 'Tank number',
          'enter_driver_name': 'Enter driver name',
          'driver_number': 'Driver Name',
          'capture_vehicle_photo': 'Capture Vehicle Photo',
          'no_litres_consumed': 'No. of litres consumed',
          'total_amount': 'Total amount',
          'eligible_amount': 'Eligible Amount',
          'eligible_litres': 'Eligible Litres',
          'total_litres': 'Total Litres',
          'total_price': 'Total Price',
          'no_of_litres': 'No. of litres',
          'no_data_found': 'No data found',
          'officer': 'Officer',
          'not_an_officer': 'Not an Officer',
          'vouchers_cards': 'Vouchers/Cards',
          'total': '|   Total',
          'something_went_wrong': 'Something went wrong, Please try again!',
          'unable_capture_photo': 'Could not capture photo!',
          'unable_fetch_mobileno': 'Unable to fetch mobile number',
          'otp_verified': 'OTP Verified',
          'otp_verify_failed': 'OTP Verification failed',
          'password_change_success': 'Password has been successfully changed!',
          'loading_image': 'Loading Image...',
          'processing': 'Processing...',
          'ok': 'OK',
          'unable_fetch_fuel_price': 'Unable to fetch fuel price',
        },
        'te': {
          'oms_full_form': 'Oil Management System',
          'login': 'Login',
          'sign_in_continue': 'Please sign in to continue',
          'user_id': 'User ID',
          'enter_username': 'Enter Username',
          'username_required': 'Username is required',
          'password': 'Password',
          'enter_password': 'Enter Password',
          'password_required': 'Password is required',
          'forgot_password': 'Forgot Password ?',
          'new_password': 'New Password',
          'new_password_req': 'New password is required',
          'change_pwd': 'Change Password',
          'sign_out': 'Sign out',
          'sign_out_prompt': 'Are you sure you want to sign out?',
          'sign_out_success': 'You have signed out successfully!',
          'sign_out_fail': 'Signout Failed!',
          'confirm_new_password': 'Confirm New Password',
          'confirm_new_password_req': 'Confirm new password is required',
          'enter_new_pwd': 'Enter New Password',
          're_enter_new_pwd': 'Re-Enter New Password',
          'next': 'Next',
          'back': 'Back',
          'no': 'No',
          'yes': 'Yes',
          'mobile_number': 'Mobile Number',
          'send_otp_desc': 'We need to send OTP to verify your number.',
          'enter_mobile_number': 'Enter mobile number',
          'mobile_number_req': 'Mobile number is required',
          'invalid_mobile_no': 'Invalid mobile number',
          'enter_otp': 'Please enter OTP',
          'enter_valid_otp': 'Please enter valid OTP',
          'otp': 'OTP',
          'sent_otp_desc': 'Please enter the OTP sent to your mobile number.',
          'fill_fuel': 'Fill Fuel',
          'reports': 'Reports',
          'fuel_fill_success': 'Fuel has been filled successfully!',
          'print': 'Print',
          'fill_fuel_confirmation': 'Are you sure you want to fill fuel ?',
          'voucher_code': 'Voucher Code',
          'enter_voucher_code': 'Enter voucher code',
          'voucher_code_cannot_empty': 'Voucher code cannot be empty',
          'tap_the_card': 'Tap the card',
          'validate': 'Validate',
          'total_available_litres': 'Total available litres',
          'total_available_amount': 'Total available amount',
          'diesel_rate_per_litre': 'Current diesel rate per litre',
          'department': 'Department',
          'designation': 'Designation',
          'fuel_type': 'Fuel type',
          'vehicle_number': 'Vehicle Number',
          'invalid_vehicle_number': "Invalid Vehicle Number",
          'enter_vehicle_number': 'Enter vehicle number',
          'vehicle_no_required': 'Vehicle number is required',
          'calculated': 'Calculated',
          'photo_required': 'Photo is required',
          'tank_number': 'Tank number',
          'enter_driver_name': 'Enter driver name',
          'driver_number': 'Driver Name',
          'capture_vehicle_photo': 'Capture Vehicle Photo',
          'no_litres_consumed': 'No. of litres consumed',
          'total_amount': 'Total amount',
          'eligible_amount': 'Eligible Amount',
          'eligible_litres': 'Eligible Litres',
          'total_litres': 'Total Litres',
          'total_price': 'Total Price',
          'no_of_litres': 'No. of litres',
          'no_data_found': 'No data found',
          'officer': 'Officer',
          'not_an_officer': 'Not an Officer',
          'vouchers_cards': 'Vouchers/Cards',
          'total': '|   Total',
          'something_went_wrong': 'Something went wrong, Please try again!',
          'unable_capture_photo': 'Could not capture photo!',
          'unable_fetch_mobileno': 'Unable to fetch mobile number',
          'otp_verified': 'OTP Verified',
          'otp_verify_failed': 'OTP Verification failed',
          'password_change_success': 'Password has been successfully changed!',
          'loading_image': 'Loading Image...',
          'processing': 'Processing...',
          'ok': 'OK',
          'unable_fetch_fuel_price': 'Unable to fetch fuel price',
        }
      };
}
