name: oepadmin
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.1
  #  dependency injection library
  get_it: ^7.1.3 #dont migrate to 7.1.4 it has dependency on async
  get_storage: ^2.0.3
  image_picker: ^0.8.4+11
  retrofit: ^3.0.1+1
  logger: ^1.1.0
  dartz: ^0.10.1
  dio_logger: ^4.0.8+8
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  connectivity_plus: ^2.2.1
  intl: ^0.17.0
  flutter_svg: ^1.0.3
  table_calendar: ^3.0.5
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.15
  flutter_spinkit: "^4.1.2"
  firebase_core: ^1.17.0
  url_launcher:
  firebase_remote_config: ^2.0.9
  firebase_analytics: ^9.1.10
  change_app_package_name: ^1.1.0
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.8
  json_serializable: ^6.1.5
  flutter_form_builder: ^7.3.1
  form_builder_validators: ^8.1.1
  firebase_storage: ^10.2.18
  image_picker: ^0.8.5+3

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: GoogleSansRegular
      fonts:
        - asset: assets/fonts/GoogleSansRegular.ttf

    - family: GoogleSansMedium
      fonts:
        - asset: assets/fonts/GoogleSansMedium.ttf
