// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeFIzEypAo0B1WEl0TyDSm53buBFACfiw',
    appId: '1:519638457474:web:9c603fea0bbf1e5753a89b',
    messagingSenderId: '519638457474',
    projectId: 'examconnect-da70a',
    authDomain: 'examconnect-da70a.firebaseapp.com',
    storageBucket: 'examconnect-da70a.appspot.com',
    measurementId: 'G-SV61MSJJL4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfedjXxtluJMIX9oJfQl3njvhoFi5LM6c',
    appId: '1:519638457474:android:c566dd104f972c7b53a89b',
    messagingSenderId: '519638457474',
    projectId: 'examconnect-da70a',
    storageBucket: 'examconnect-da70a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPRKMKDQtrrkQSFlrndt6ENvPlFWgTrEs',
    appId: '1:519638457474:ios:aba2929e96b77f5d53a89b',
    messagingSenderId: '519638457474',
    projectId: 'examconnect-da70a',
    storageBucket: 'examconnect-da70a.appspot.com',
    iosClientId: '519638457474-2ukhvn1c27ig4ieei9vni4kb0avi86jn.apps.googleusercontent.com',
    iosBundleId: 'com.example.oepadmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPRKMKDQtrrkQSFlrndt6ENvPlFWgTrEs',
    appId: '1:519638457474:ios:aba2929e96b77f5d53a89b',
    messagingSenderId: '519638457474',
    projectId: 'examconnect-da70a',
    storageBucket: 'examconnect-da70a.appspot.com',
    iosClientId: '519638457474-2ukhvn1c27ig4ieei9vni4kb0avi86jn.apps.googleusercontent.com',
    iosBundleId: 'com.example.oepadmin',
  );
}
